carritoapp/urls.py
from django.urls import path

from .import views

app_name = "carrito"

urlpatterns = [
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carrito, name="limpiar"),
]

pedidos/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.procesar_pedido, name="procesar_pedido"),
]

proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),  
    path('', include('approyecto.urls')) ,
    path('servicios/', include('serviciosapp.urls')),
    path('contacto/', include('contactoapp.urls')),
    path('tienda/', include('tiendapp.urls')),
    path('carrito/', include('carritoapp.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('pedidos/', include('pedidos.urls')),
]

tiendapp/urls.py
from django.urls import path, include
from tiendapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.tienda, name="Tienda"),
]

tiendapp/models.py
from django.db import models

# Create your models here.

class CategoriaProducto(models.Model):
    nombre = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = "categoriaProd"
        verbose_name_plural = "categoriasProd"
    
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    categorias = models.ForeignKey(CategoriaProducto, on_delete=models.CASCADE) # clave foranea
                                                                                # para relacionar
                                                                                # la clase Producto con CategoriaProducto
    precio = models.FloatField()
    imagen = models.ImageField(upload_to="tienda", null=True, blank=True)       
    disponibilidad = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    
    updated = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"
    

tiendapp/views.py
from django.shortcuts import render
from .models import Producto


# Create your views here.

def tienda(request):
    productos = Producto.objects.all()
    
    return render(request, "tienda/tienda.html", {"productos": productos})

tiendapp/templates/carro/widget.html
<table class="table table-bordered" style="color: white;">
    <thead>
        <tr>
            <th colspan="3" class="text-center">
                Carro compras
            </th>
        </tr>
        <tr>
            <th>
                Producto
            </th>
            <th>
                Cantidad
            </th>
            <th>
                Suma
            </th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.carrito.items %}

        {% for key, value in request.session.carrito.items  %}
        <tr class="text-center">
            <td>{{value.nombre}}</td>
            <td>{{value.cantidad}}</td>
            <td>
                <a href="{% url 'carrito:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                <a href="{% url 'carrito:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a><br/>
                {{value.precio}} $

            </td>
        </tr>
        {% endfor %}

        {% else %}

        <tr>
            <td colspan="3">
                <div class="alert alert-danger text-center">Sin productos</div>
            </td>
        </tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">

                Total: {{importe_total_carrito}} $

            </td>
        </tr>

        {% if request.session.carrito.items %}

        <tr>

            <td colspan="3" style="text-align: center">
                <a href="../pedidos" class="btn btn-success">Hacer Pedido</a>
            </td>


        </tr>
        {% endif %}

    </tfoot>

</table>